language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev

# Add any extra services that travis can use
services:
  - postgresql

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"

# Commands run before running scipt command
before_script:
  - psql -c 'create database test_db;' -U postgres

# command to run tests
script: python manage.py test_coverage

# Commands run after the script command
after_success: coveralls