"""empty message

Revision ID: 0473bace3f32
Revises: 8b77b8401e09
Create Date: 2017-08-09 15:05:26.935910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0473bace3f32'
down_revision = '8b77b8401e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fname', sa.String(length=25), nullable=False))
    op.add_column('user', sa.Column('lname', sa.String(length=25), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lname')
    op.drop_column('user', 'fname')
    # ### end Alembic commands ###
