"""empty message

Revision ID: 5594f8f711cc
Revises: f4ea7f9c94e6
Create Date: 2017-08-25 07:17:55.752564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5594f8f711cc'
down_revision = 'f4ea7f9c94e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('black_list_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.drop_index('ix_bucket_list_name', table_name='bucket_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_bucket_list_name', 'bucket_list', ['name'], unique=False)
    op.drop_table('black_list_token')
    # ### end Alembic commands ###
